language: php
sudo: false

php:
  - '8.0'

before_script:
  - composer update

script:
  - ./vendor/bin/phpcs --standard=PSR2 -n src
  - ./vendor/bin/parallel-lint src
  - ./vendor/bin/psalm
  - ./vendor/bin/phpunit -v
